### ISSUE TITLE
Question about module property in package.json 

### ISSUE THREAD

**Issue by nicolaibach** [simonplend/node-shell-scripting-with-zx#2]
Hi and thank you for the nice article on sitpoint!

In the bootstrap-tool example, the `selectedModuleSystem` is assigned to the `module` property in `package.json`. I was wondering why not the `type` property?

**Comment by simonplend** [comment]
This is an error in my article, it should be `type` — thanks for catching this and letting me know!

It's great to hear that you enjoyed the article :)

**Comment by nicolaibach** [comment]
I replay did enjoy the article. 
Thanks for the reply.

**Comment by simonplend** [comment]
Fixed in the bootstrap tool in this repository. I've opened a pull request which fixes it in the article — the changes will hopefully go live early next week.

Thanks again @nicolaibach!
